CLI hw
shavkunov/software-design pull request #1
Opened 2018-03-17 16:53 UTC by shavkunov

2018-03-26 14:30 UTC, yurii-litvinov requested changes
- неправильное имя команды совсем убивает шелл, что нехорошо --- вдруг юзер просто опечатался
- то же самое с grep --- ошибка в формате команды убивает весь шелл, так быть не должно

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/arch.md
> +Возвращается в итоге объект типа ExecutionResult, содержащий вывод команды, а также флаг нужно ли завершится(команда Exit может завершать сессию с пользователем)
В русском языке, в отличие от Java, пробел перед `(` ставится. И вообще как-то много опечаток, диплом будет писать тяжело. Или читать :)

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/CommandLine.kt
> +            } catch (e: Exception) {
Ловить совсем все исключения плохо, так и NullPointerException поймается, и прочие ненужные штуки. Имеет смысл ловить только те исключения, про которые мы знаем, откуда они взялись и можно ли продолжить работу.

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/Exceptions.kt
> +class EmptyCommandException : Exception()
Исключениям тоже надо комментарии

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/commands/AssignmentOperator.kt
> +data class AssignmentOperator(val name: String, val value: String) : SystemOperator {
Ну и операторам тоже по-хорошему нужны комментарии

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/PipelineParser.kt
> +        val pipeSplit = InputHandler.split(input, { it.character == delimeter } )
Получилась циклическая зависимость с InputHandler. Кажется, InputHandler можно разделить на два класса, чтобы её не было

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/Preprocessor.kt
> +                return true
Можно было просто `return char != substitution`

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/Preprocessor.kt
> +    fun process(string: String): List<EscapeChar> {
public-методам тоже нужен комментарий, по идее

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/Tokenizer.kt
> +        var input = input
Предупреждение компилятора, нехорошо

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/test/kotlin/operators/PIpeline.kt
> +class PIpelineTest {
P**i**pelineTest :)

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/test/kotlin/Environment.kt
> +        assertEquals(false, result.isExit)
assertFalse?

2018-03-26 14:30 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/Main.kt
> +    environment.addUtility("wc", WordCount)
А grep? :)

2018-03-29 23:53 UTC, shavkunov commented
Спасибо Вам за ваши замечания.

Все мелкие неточности в коде я подправил. Также я попытался немного подправить описание архитектуры, возможно, стало получше.

2018-04-22 10:32 UTC, yurii-litvinov requested changes
Некоторые тесты не проходят, потому что в них создаётся пустой Environment и в нём пытаются исполниться команды (которые, наверное, исполняются на линуксе как внешние, но под виндой таких нет).

Grep всё ещё падает на некорректном вводе (я там ниже в комментарии написал, где). Давайте CLI будет зачтена, а Grep надо будет поправить (и заодно поправить тесты и мелкие замечания).

2018-04-22 10:32 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/Environment.kt
> +        } catch (e: Exception) {
Дело может быть не только в неправильном вводе, но и в чём угодно. Я бы советовал ловить более специфические исключения. Но так всё-таки лучше, чем было :)

2018-04-22 10:32 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/Preprocessor.kt
> +        when(escaping) {
Нужен пробел перед "(" :)

2018-04-22 10:32 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/StringCommon.kt
> +object StringCommon {
И этой штуке нужен комментарий

2018-04-22 10:32 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/utilities/Common.kt
> +fun getFileContent(path: Path): String {
И даже этой штуке по-хорошему нужен комментарий

2018-04-22 10:32 UTC, yurii-litvinov commented on cli/src/main/kotlin/ru/spbau/shavkunov/utilities/Grep.kt
> +            additionalLines = Integer.valueOf(text)
Так падает, если пользователь ошибся и за А не число. Пользователю нельзя доверять

2018-05-19 02:17 UTC, shavkunov reviewed
Подправил Ваши замечания. Извиняюсь за задержку

2018-05-19 02:17 UTC, shavkunov commented on cli/src/main/kotlin/ru/spbau/shavkunov/Environment.kt
> +        } catch (e: Exception) {
Исправил на catch более конкретных исключений.

2018-05-19 02:17 UTC, shavkunov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/Preprocessor.kt
> +        when(escaping) {
Исправил.

2018-05-19 02:17 UTC, shavkunov commented on cli/src/main/kotlin/ru/spbau/shavkunov/interpreter/StringCommon.kt
> +object StringCommon {
Добавлен

2018-05-19 02:17 UTC, shavkunov commented on cli/src/main/kotlin/ru/spbau/shavkunov/utilities/Common.kt
> +fun getFileContent(path: Path): String {
Добавил

2018-05-19 02:17 UTC, shavkunov commented on cli/src/main/kotlin/ru/spbau/shavkunov/utilities/Grep.kt
> +            additionalLines = Integer.valueOf(text)
Добавил исключение неправильного аргумента, как это делает настоящий grep

2018-06-01 14:12 UTC, yurii-litvinov approved these changes
Ага, всё ок, grep зачтена

2018-06-01 22:25 UTC, merged